### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Alexandr21Smirnov** [Alexandr21Smirnov/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Alexandr21Smirnov21collaborator** [comment]
**― How's it going brothers, my name is Donald Trump. I'm very shy and the same time I'm the coolest president of USA of all time. I have expensive car and beautiful wife and you have infilation(loser). Many people think that I am a Russian spy, but I am not, because ― I don't think so. Good luck and have fun and please don't cry as usual...**
