### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Alexandr21Smirnov** [Alexandr21Smirnov/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Alexandr21Smirnov21collaborator** [comment]
PERSONAL LIFE

1946
I'm was born (Finally)

1977
Married Czech model Ivana Zelníčková (Yep)

1977
My first son is born. I called him Donald (Obviously)

1982
Birth of Ivanka Trump (I want to called Donald too, but wife...)

1984
Birth of Eric Trump (I'm very liked Eric Clapton)

1992
Affair with actress Marla Maples and divorce Ivana (Double kill)

1993
Married Marla and had a daughter, we named her Tiffany (Cause I can)

1999
Divorced Marla (So bad)

2005
Married Slovenian model Melania Knauss (Love this country)

2006
Melania gained United States citizenship and gave birth to our son, Barron (I guess, take a pause)

EDUCATION

1964
Enrolled at Fordham University (Why me)

1966
Transferred to the Wharton School of the University of Pennsylvania (Here were go againg)

1966
I was deemed fit for military service based upon a medical examination (Cool story)

1968
Graduated with a B.S. in economics (Really?)

EXPERIENCE

1968
Began my business career at my father's real estate development company, Elizabeth Trump & Son (Just a business)

1971
Was promoted to president of the company and renamed it The Trump Organization (Greatness)

1978
Purchased a 50 percent stake in the derelict Commodore Hotel and turned it into the Grand Hyatt Hotel in 2 years of remodeling (That was easy)

1983
I purchased New Jersey Generals, an American football team! (Cause I'm playing FIFA)

1987
Registered as a Republican (You should be fighting evil instead of joining it)

1988
Acquired the Plaza Hotel in Manhattan for $407 million, rename him on "the Mona Liza" invested $50 million to restore the building and boosted it from three-star to four-star hotel. (I'm so clever)

1989, 1990
Learned about Tour de France and decided to hold my very own Tour de Trump. (Genius, Genius, Genius)

1989 ― 1992
Ran a second hand airline called Trump Shuttle. (I must be in all areas)

1994
Refurbished the Gulf and Western Building on Columbus Circle, turned it into a 44-story luxury property known as Trump International Hotel and Tower (More Trump in the title)

1996
Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building (Ironically?)

1997
Began a multi-building development along the Hudson River, which was named Trump Place. Me and the other investors sold our shares for $1.8 billion and that was then the biggest residential sale in the history of New York City (Shut up and take my money)

1999
I'm switched to the Reform Party. (Wrong Turn)

2001
I'm joined the Democratic Party (Wrong Turn 2)

2002
Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the Trump Park Avenue. (Em, you know it)

2005
Started Trump University with Michael Sexton and Jonathan Spitalny: no grades, certificates and other crud, but program offered courses in real estate, asset management entrepreneurship, and wealth creation. 98% students gave positive reviews while studying (Clear business!)

2009
Became Republican again (Stack overflow)

2015
Became the most important Republican nominating for presidential election run (Сhoice without option)

2016
Won election race with 77 votes more than Clinton (You thought, that I wouldn't outplay you)

2017
Became 45th president of the United States (Game over, I'm won this life)

2019
House Speaker Nancy Pelosi initiated a formal impeachment inquiry (Traitor)

MEDIA CAREER

1987
Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz (I'm starting writing interesting books)

1990
Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen

1991
Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"

1997
Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner

2000
Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett

2003 ― 2015
Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"

2004
Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver

2004
Published a book "The Way to the Top: The Best Business Advice I Ever Received"

2004
Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver

2004 ― 2008
Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)

2005
Performed a song with Megan Mullally at the 57th Primetime Emmy Awards

2005
Published a book "The Best Golf Advice I Ever Received

2006
Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver

2006
Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"

2006
Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"

2007
Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant

2007
Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker

2009
Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver

2011
Published a book "Trump Tower" in coauthorship with Jeffrey Robinson

2011
Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki

2015
Published a book "Crippled America: How to Make America Great Again"(while enough)

2019
Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9" (WHAT?)
